/*
  # Family Dynasty Feature

  1. Schema Changes
    - `farming_groups` — add `head_user_id` column (the current family head; defaults to creator)
    - `group_members` — add `linked_user_id` (links to a real Supabase auth account) and `is_custodian_child` flag
  
  2. New Tables
    - `family_invites` — invite codes generated by the head, 7-day expiry, single-use
    - `family_join_requests` — any user can request to join; head accepts/rejects
    - `family_messages` — family-wide group chat; head + linked members only

  3. Security
    - RLS enabled on all new tables
    - Head-only operations: generate invites, accept/reject requests, transfer headship, manage members
    - Linked members: read/write messages, read group data
    - Any auth'd user: look up invite by code (needed for join flow)
*/

-- ─── farming_groups: add head_user_id ────────────────────────────────────────

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'farming_groups' AND column_name = 'head_user_id'
  ) THEN
    ALTER TABLE farming_groups
      ADD COLUMN head_user_id uuid REFERENCES user_profiles(id) ON DELETE SET NULL;
  END IF;
END $$;

-- Backfill: existing groups keep their creator as head
UPDATE farming_groups SET head_user_id = user_id WHERE head_user_id IS NULL;

-- ─── group_members: add linked_user_id + is_custodian_child ──────────────────

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'group_members' AND column_name = 'linked_user_id'
  ) THEN
    ALTER TABLE group_members
      ADD COLUMN linked_user_id uuid REFERENCES user_profiles(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'group_members' AND column_name = 'is_custodian_child'
  ) THEN
    ALTER TABLE group_members
      ADD COLUMN is_custodian_child boolean NOT NULL DEFAULT false;
  END IF;
END $$;

-- ─── family_invites ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS family_invites (
  id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id       uuid        NOT NULL REFERENCES farming_groups(id) ON DELETE CASCADE,
  code           text        NOT NULL UNIQUE,
  created_by     uuid        REFERENCES user_profiles(id) ON DELETE SET NULL,
  expires_at     timestamptz NOT NULL,
  used_by_user_id uuid       REFERENCES user_profiles(id) ON DELETE SET NULL,
  used_at        timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE family_invites ENABLE ROW LEVEL SECURITY;

-- Head can manage invites for their own group
CREATE POLICY "Head can manage own group invites"
  ON family_invites
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM farming_groups fg
      WHERE fg.id = family_invites.group_id
        AND (fg.head_user_id = auth.uid() OR fg.user_id = auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM farming_groups fg
      WHERE fg.id = family_invites.group_id
        AND (fg.head_user_id = auth.uid() OR fg.user_id = auth.uid())
    )
  );

-- Any authenticated user can look up an invite by code (needed for join flow)
CREATE POLICY "Authenticated users can look up invite codes"
  ON family_invites
  FOR SELECT
  TO authenticated
  USING (true);

-- ─── family_join_requests ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS family_join_requests (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id            uuid        NOT NULL REFERENCES farming_groups(id) ON DELETE CASCADE,
  requester_user_id   uuid        NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  message             text,
  status              text        NOT NULL DEFAULT 'pending'
                                  CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE family_join_requests ENABLE ROW LEVEL SECURITY;

-- Any user can submit a join request
CREATE POLICY "Users can submit join requests"
  ON family_join_requests
  FOR INSERT
  TO authenticated
  WITH CHECK (requester_user_id = auth.uid());

-- Users can view their own requests
CREATE POLICY "Users can view own join requests"
  ON family_join_requests
  FOR SELECT
  TO authenticated
  USING (requester_user_id = auth.uid());

-- Head can view and act on requests for their group
CREATE POLICY "Head can manage join requests for their group"
  ON family_join_requests
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM farming_groups fg
      WHERE fg.id = family_join_requests.group_id
        AND (fg.head_user_id = auth.uid() OR fg.user_id = auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM farming_groups fg
      WHERE fg.id = family_join_requests.group_id
        AND (fg.head_user_id = auth.uid() OR fg.user_id = auth.uid())
    )
  );

-- ─── family_messages ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS family_messages (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id        uuid        NOT NULL REFERENCES farming_groups(id) ON DELETE CASCADE,
  sender_user_id  uuid        REFERENCES user_profiles(id) ON DELETE SET NULL,
  sender_name     text        NOT NULL,
  message         text        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE family_messages ENABLE ROW LEVEL SECURITY;

-- Head OR any linked member of the group can read + write messages
CREATE POLICY "Head and linked members can read messages"
  ON family_messages
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM farming_groups fg
      WHERE fg.id = family_messages.group_id
        AND (fg.head_user_id = auth.uid() OR fg.user_id = auth.uid())
    )
    OR
    EXISTS (
      SELECT 1 FROM group_members gm
      JOIN farming_groups fg ON fg.id = gm.group_id
      WHERE fg.id = family_messages.group_id
        AND gm.linked_user_id = auth.uid()
    )
  );

CREATE POLICY "Head and linked members can send messages"
  ON family_messages
  FOR INSERT
  TO authenticated
  WITH CHECK (
    sender_user_id = auth.uid()
    AND (
      EXISTS (
        SELECT 1 FROM farming_groups fg
        WHERE fg.id = family_messages.group_id
          AND (fg.head_user_id = auth.uid() OR fg.user_id = auth.uid())
      )
      OR
      EXISTS (
        SELECT 1 FROM group_members gm
        WHERE gm.group_id = family_messages.group_id
          AND gm.linked_user_id = auth.uid()
      )
    )
  );

-- ─── Indexes for performance ──────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_family_invites_code         ON family_invites(code);
CREATE INDEX IF NOT EXISTS idx_family_invites_group        ON family_invites(group_id);
CREATE INDEX IF NOT EXISTS idx_family_join_requests_group  ON family_join_requests(group_id);
CREATE INDEX IF NOT EXISTS idx_family_join_requests_user   ON family_join_requests(requester_user_id);
CREATE INDEX IF NOT EXISTS idx_family_messages_group       ON family_messages(group_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_group_members_linked        ON group_members(linked_user_id);
CREATE INDEX IF NOT EXISTS idx_farming_groups_head         ON farming_groups(head_user_id);
